### ISSUE TITLE
Player nameplate shows Blizzard power bar and special resources

### ISSUE THREAD

**Issue by Adirelle** [oUF-wow/oUF#578] opened 2021-03-13 18:49 UTC
**Describe the bug**
Blizzard power bar and resource widget are displayed along the custom nameplate for the player.

**How to reproduce**
1. Create and use a nameplate style for oUF that does not display power bar nor special resources.
2. Check "personal resource display" in Blizzard interface settings (Names tab).
3. Select a target, or enter in combat so the player nameplate is shown.

**What did you expect?**
A customized nameplate without power bar  nor special resource.

**Error report**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/24633/111040616-09a66e00-8434-11eb-9aec-a34fb815ab76.png)

Please note that enabling "Show special resource on target" move the special resource on the target nameplate.

**Comment by Adirelle** [comment] 2021-03-13 18:56
This might be related to #525. However, I am neither messing with Blizzard code nor oUF one/.

In its current version, oUF does not hide Blizzard frames (ClassNameplate*) for the unit "player", see ClassNameplate files in https://github.com/Gethe/wow-ui-source/tree/live/AddOns/Blizzard_NamePlates

**Comment by ls-** [comment] 2021-03-14 01:13
It's not a bug. What @Adirelle said is correct, we do so to avoid messing with forbidden nameplates in dungeons, they still use the same insecure class power widgets. It's also opens up an option of repurposing default class power widgets instead of creating your own. So if a user wants to disable Blizz widgets, they should do it themselves, something like this should do the trick.

```lua
if NamePlateDriverFrame.classNamePlatePowerBar then
	NamePlateDriverFrame.classNamePlatePowerBar:Hide()
	NamePlateDriverFrame.classNamePlatePowerBar:UnregisterAllEvents()
end

hooksecurefunc(NamePlateDriverFrame, 'SetupClassNameplateBars', function(nameplate)
	if(not nameplate or nameplate:IsForbidden()) then
		return
	end

	if(nameplate.classNamePlateMechanicFrame) then
		nameplate.classNamePlateMechanicFrame:Hide()
	end

	if(nameplate.classNamePlatePowerBar) then
		nameplate.classNamePlatePowerBar:Hide()
		nameplate.classNamePlatePowerBar:UnregisterAllEvents()
	end
end)
```

I used to run something similar myself, not sure if it still works. I could possibly add it as an option to `oUF:SpawnNamePlates`, something like `disableBlizzPower` toggle, but idk.

**Comment by Adirelle** [comment] 2021-03-14 08:17
I am using the same kind of workaround. I have got no tainting errors so far.

IMO the current behavior is a bit misleading. Some additional doc about SpawnNameplates  could be sufficient. My apologies if they existed and I have overlooked them.

**Comment by ls-** [comment] 2021-03-14 08:45
@Adirelle nah, nah, all good and I agree. I was the one wrote all that bs anyway, so it's on me. I'll talk to other guys about adding the option I mentioned.

**Comment by Adirelle** [comment] 2021-03-14 16:36
It seems it still cause tainting.

**Comment by Adirelle** [comment] 2021-03-14 17:29
There is something funny.

My master branch causes tainting, but my last tag does not. Between the two, I mainly removed all shadowing of globals: https://github.com/Adirelle/oUF_Adirelle/compare/9.0-1.1.0-beta-4...master

**Comment by ls-** [comment] 2021-03-15 01:56
It is one of these by any chance?
```
1x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
```
You can get it even without a single nameplate addon, seems like a generic API taint.

**Comment by Adirelle** [comment] 2021-03-15 02:00
Nope, something about calling SetTargetClampingInsets, [line 305 of Blizzard_NamePlates/Blizzard_NamePlates.lua](
https://github.com/Gethe/wow-ui-source/blob/24674a74f73fc71de42aa3970505a5097c58645a/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua#L305)

Curiously, it goes away when I revert my changes and upvalue all the globals ; I have a script that automates it. I am wondering if another addon is somehow involved.

**Comment by ls-** [comment] 2021-03-15 02:10
Oh, yeah, that's the other one T_T I don't remember what's causing it tho.

**Comment by siweia** [comment] 2021-04-14 15:22
It is much more easier to just disable system player plate, then create another player frame and make it looks like a player plate, which you don't need to worry about taint.

**Comment by p3lim** [comment] 2024-04-17 17:28
@siweia has the best answer to this, closing it with an example:

```lua
oUF:SpawnNamePlates(nil, nil, {nameplateShowSelf = '0'})
```

**Closed by p3lim** 2024-04-17 17:28 UTC
Labels: bug
