### ISSUE TITLE
Updated ClassIcons for Destro Warlock

### ISSUE THREAD

**Issue by PProvost** [oUF-wow/oUF#183] opened 2013-03-26 01:56 UTC
Hey haste,

I made some mods to classicons.lua so the same soul-shards icon system works for destruction lock burning embers.

You can see the edits here:
https://github.com/PProvost/ouf_quaiche/commit/624d52223309bee06397a756e48060c8da214b7d

If you'd prefer I can do a clone and pull request, but given the elegance of your lua code I suspect you'll have a neater way to do it than I did.

Regards,

PProvost

**Comment by p3lim** [comment] 2015-11-15 13:09
No longer needed in Legion, see #260.

**Comment by haste** [comment] 2015-11-15 13:15
On one side Legion won't be out until Q2/Q3 next year, so closing the issue is kinda stupid, but on the other hand... We're still not supporting it after so many years. :P

**Comment by p3lim** [comment] 2015-11-15 13:29
Was adding the note mostly to link the two issues together so it won't be forgotten once Legion came :)

**Closed** 2016-09-11 09:16 UTC
