### ISSUE TITLE
Possible issue on new boss Antoran High Command (vehicle override)

### ISSUE THREAD

**Issue by Blazeflack** [oUF-wow/oUF#402] opened 2017-11-28 21:31 UTC
Hi.

We have received a report from a user of ElvUI that people who enter the vehicles (Legion Command Pod) during the new Antoran High Command raid boss, have their raid frame turned into a vehicle, which he is unable to target in the usual left-click way. He has to use a /target command instead. I'm not raiding or even actively playing WoW myself, so I am unable to confirm or debug this properly.

While I understand that there are times where the layout is at fault, especially with the kind of modifications ElvUI makes, I thought I would put out a feeler here just in case. There have been some changes in oUF recently regarding vehicles, so it's not too far off to think that this could be an unintentional side-effect.

If any of you guys happen to notice anything, or if you can confirm that your own layout works just fine on that boss, then please let me know here.

Thank you.

**Comment by p3lim** [comment] 2017-11-28 21:38
Are you using oUF 7.x in ElvUI now?

**Comment by Blazeflack** [comment] 2017-11-28 22:14
Hi p3lim.

Yes we are up-to-date with latest changes from the master branch here.

**Comment by p3lim** [comment] 2017-11-28 22:30
Alright, I don't raid myself so I can't really test it, but it seems unintentional indeed.

**Comment by Blazeflack** [comment] 2017-11-28 23:05
I appreciate your input, thank you. The raid just opened this week so hopefully other people will be able to confirm or deny it soon-ish.

**Comment by Grimsbain** [comment] 2017-11-29 03:29
I raid using a normal oUF raid layout and it is indeed messing up on the pods. When the person gets in their heal stops updating.

**Comment by Blazeflack** [comment] 2017-11-29 04:10
Thanks for the confirmation @Grimsbain

**Comment by Grimsbain** [comment] 2017-11-29 09:01
I don't know enough about the backend side of oUF to suggest what code needs to be fixed but the [changes to CompactUnitFrame_UpdateInVehicle](https://www.townlong-yak.com/framexml/24920/CompactUnitFrame.lua/diff) in 7.3 may be a clue to what is needed.

**Comment by p3lim** [comment] 2017-11-29 09:38
Leaving the original ticket from ElvUI here too.
https://git.tukui.org/elvui/elvui/issues/220

Blizzard seems to have flip-flopped the vehicle logic, we'll investigate further and get a fix out soon™.

**Comment by p3lim** [comment] 2017-11-29 10:05
Can any of you confirm that players in pods are targetable with the default raid frames?

By the looks of the default implementation, Blizzard seems to have disabled all vehicle logic completely.

**Comment by ls-** [comment] 2017-11-29 10:13
Heh, Blizz disabled vehicle display on their raid frames entirely due to necessity to heal players in pods. Basically we're dealing Blizz hacks, again...

So far it looks like we'll have to do the same and then revert this hack when Blizz fix their stuff by either removing said hack (likely) or adding necessary API and implementing things properly (unlikely) :grin::gun:

**Comment by Grimsbain** [comment] 2017-11-29 10:32
I disabled my raid layout after our first wipe and used the default UI and it worked.

**Comment by p3lim** [comment] 2017-11-29 10:52
@Grimsbain Just to confirm, could you **target** the players inside the pods using the default raid frames by **clicking** them?

**Comment by ls-** [comment] 2017-11-29 10:59
To be a bit more precise. Did target frame show up for a person in pod whose raid frame you clicked? :grin::gun:

**Comment by Grimsbain** [comment] 2017-11-29 11:06
I use mouseover macros for my heals and my memory of the fight isn't clear enough to say for sure. But I think someone else that switched said it worked also when people entered the pod their health bar didn't change.

**Comment by p3lim** [comment] 2017-11-29 11:14
The health bar one can be explained, but by default (even in the default raid frames), you can't target a player inside a vehicle, which is what we're trying to confirm is still the same or not.

**Comment by ls-** [comment] 2017-11-29 11:26
We're asking this questions because of `This prevents me from healing them unless I /tar playername.` in elvUI report.

It should be impossible to do so, whereas that person claims that s/he's doing that, so we're trying to figure out what we're supposed to do :p Either temporarily nuke vehicle handling on raid frames or something else...

**Comment by ls-** [comment] 2017-11-29 11:39
We're asking these questions because of `This prevents me from healing them unless I /tar playername.` in elvUI's report.

One shouldn't be able to actually target anyone who's in a vehicle via clicking or /tar. Focus and mouseover stuff works just fine though, we're trying to figure out how to deal w/ this whole thingy.

IMHO, we'll just break vehicle handling on raid frames for now and then rever it when Blizz either undo their hack or add proper API to handle this case correctly.

**Comment by p3lim** [comment] 2017-11-29 11:43
Confirmed that units have been changed, we'll push a fix for this soon.

**Comment by Blazeflack** [comment] 2017-11-29 12:08
Good work guys. I leave for work and check back a few hours later and you have more or less already isolated and fixed the issue. Cheers.

**Comment by Zephareth** [comment] 2017-11-30 15:45
I use Grid2 and Clique, same issue. When i try to heal the Capsule i heal only myself.
I opend the Blizzard standart Raid frame and healed them with clique, normaly.
Sry i know  this isnt the Grid2 forum but maybe my Information helps.

**Comment by klousy** [comment] 2017-11-30 17:11
VuhDo obviously had the same problem. They temporarely disabled the vehicle support in VuHDo (not officialy, just the alpha version), but also Malygos fights are broken with this workaround.

**Comment by Rainrider** [comment] 2017-11-30 21:50
Please test #403 and share your results. With it you need to spawn raidpets/partypets if you want to see the raid/party vehicles in encounters like Malygos.

**Comment by p3lim** [comment] 2017-12-01 00:15
Got a response from a Blizzard official that this change was not intentional and that they are still working on the vehicle implementation for raid frames.

> my understanding is that UnitHasVehicleUI returns true when it's a full vehicle replace (action bars change and all that), however some crazy mechanics place you into a vehicle temporarily (like a boss grabbing you) and UnitTargetsVehicleInRaidUI should return false, it should still target the player, not the vehicle
> ...
> I don't think macros have a conditional equivalent to UnitHasVehiclePlayerFrameUI atm

*UnitTargetsVehicleInRaidUI* is a new API that I haven't seen before, so I suppose this was the intention behind it.

We'll still let #403 through because we'll have to make sure things work for encounters that are more relevant to the average player (current content), but we'll have to revert it at some point (7.3.5 is coming out at some point, probably will be fixed there since this is indeed a bug).

**Comment by p3lim** [comment] 2017-12-01 01:59
> VuhDo obviously had the same problem. They temporarely disabled the vehicle support in VuHDo (not officialy, just the alpha version), but also Malygos fights are broken with this workaround.

I told the author of VuhDo to do that :p

**Comment by Blazeflack** [comment] 2017-12-03 06:43
I believe this can be closed now.

**Closed** 2017-12-03 07:46 UTC
Labels: bug, core

**Comment by klousy** [comment] 2017-12-03 13:54
Works great, very good job guys, especially to p3lim :P

**Comment by p3lim** [comment] 2017-12-03 15:01
@ls- did most of the work, but thanks :p

**Comment by p3lim** [comment] 2017-12-07 14:46
Blizzard fixed this issue for their own raid frames in build 25632, we'll see if they fix it for the secure stuff we use as well.

**Comment by p3lim** [comment] 2017-12-07 18:02
Got a confirmation that a fix for the secure headers will be in the next PTR.
